replicaCount: 2

image:
  repository: avadhootacr001.azurecr.io/enterprise-app
  tag: "c8de79b0bfe36cdf3c464099d9361c6819b41072"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  host: enterprise.local

hpa:
  minReplicas: 2
  maxReplicas: 10
  cpu: 70
