replicaCount: 2

image:
  repository: avadhootacr001.azurecr.io/enterprise-app
  tag: "f4e99533ab3785638b5115367b8eb6de038bbe19"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  host: enterprise.local

hpa:
  minReplicas: 2
  maxReplicas: 10
  cpu: 70
