replicaCount: 2

image:
  repository: portainer22.azurecr.io/enterprise-app
  tag: "765e990907fdb2b76eae9df03399045713a24d58"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  host: enterprise.local

hpa:
  minReplicas: 2
  maxReplicas: 10
  cpu: 70
