apiVersion: apps/v1
kind: Deployment

metadata:
  name: enterprise-app

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: enterprise-app

  template:
    metadata:
      labels:
        app: enterprise-app

    spec:
      containers:
      - name: enterprise-app

        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

        ports:
        - containerPort: 80

        resources:
          {{- toYaml .Values.resources | nindent 10 }}
