name: Build-Push-Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Verify Azure Resources
        run: |
          az account show
          az acr show --name avadhootacr001 --query loginServer -o tsv

      - name: Login to Azure Container Registry
        run: |
          az acr login --name avadhootacr001

      - name: Verify Repository Structure
        run: |
          echo "Current Directory:"
          pwd

          echo "Dockerfiles:"
          find . -name Dockerfile

          echo "Requirements Files:"
          find . -name requirements.txt

          echo "Values Files:"
          find . -name values.yaml

          echo "App Directory Contents:"
          ls -la enterprise-gitops-platform/app || true

          echo "Full Repository Structure:"
          find . -type f | sort

      - name: Build Docker Image
        run: |
          docker build --no-cache \
            -f enterprise-gitops-platform/app/Dockerfile \
            -t avadhootacr001.azurecr.io/enterprise-app:${{ github.sha }} \
            enterprise-gitops-platform/app

      - name: Trivy Security Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: avadhootacr001.azurecr.io/enterprise-app:${{ github.sha }}
          format: table
          exit-code: 0

      - name: Push Docker Image
        run: |
          docker push avadhootacr001.azurecr.io/enterprise-app:${{ github.sha }}

      - name: Update Helm Image Tag
        run: |
          sed -i "s/tag:.*/tag: \"${{ github.sha }}\"/g" \
          helm/enterprise-app/values.yaml

      - name: Commit Helm Changes
        run: |
          git config --global user.name "avadhutpatil22"
          git config --global user.email "patilavadhut907@gmail.com"
          
          git add helm/enterprise-app/values.yaml

          git commit -m "Update image tag to ${{ github.sha }}" || echo "No changes to commit"

          git push
