name: Build-Push-Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Verify Azure Subscription
        run: |
          az account show
          az acr show --name portainer22 --query loginServer -o tsv

      - name: Login to Azure Container Registry
        run: |
          az acr login --name portainer22

      - name: Build Docker Image
        run: |
          docker build \
            -t portainer22.azurecr.io/enterprise-app:${{ github.sha }} \
            .

      - name: Trivy Security Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: portainer22.azurecr.io/enterprise-app:${{ github.sha }}
          format: table
          exit-code: 0

      - name: Push Docker Image
        run: |
          docker push \
            portainer22.azurecr.io/enterprise-app:${{ github.sha }}

      - name: Update Helm Image Tag
        run: |
          sed -i "s/tag:.*/tag: \"${{ github.sha }}\"/g" helm/enterprise-app/values.yaml

      - name: Commit Helm Changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          git add helm/enterprise-app/values.yaml

          git commit -m "Update image tag to ${{ github.sha }}" || echo "No changes to commit"

          git push
